import Head from 'next/head'
import {BsFillMoonFill} from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillGithub, AiFillLinkedin } from 'react-icons/ai'
import Image from 'next/image'
import devdel from '../public/abel-oua.jpeg'
import design from '../public/1.png'
import code from '../public/2.png'
import consulting from '../public/3.png'
import { useState } from 'react'
import web1 from "../public/nft2.jpg";
import web2 from "../public/movies.png";
import web3 from "../public/explore.png";
import web5 from "../public/nft3.png";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>D3vD3l Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devdelLogoBlack.png" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-20 py-4 md:py-4 lg:py-4 dark:bg-gray-900  border-4 border-teal-400'>

        <section className="min-h-screen">
          <nav className='py-6 mb-6 flex justify-between'>
            <a href="#"><h1 className='text-xl text-gray-700 font-Changa font-semibold dark:text-gray-100'>D3vD3l</h1></a>
            <ul className='flex items-center'>
              <li><BsFillMoonFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-gray-800 dark:text-white' /></li>
              <li><button type="button" class="text-gray-900 hover:text-white border border-gray-800 hover:bg-gray-900 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg px-4 py-2 ml-6 text-center dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800"><a href='https://drive.google.com/file/d/1x1ZvFSkvvXo5rsv8DcYo4JtNiO4lh-GH/view?usp=sharing' target="_blank">Resume</a></button></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className=' md:text-5xl text-3xl py-2 text-teal-600 font-medium'>Abdelhadi El Ouaraguli</h2>
            <h3 className='md:text-xl text:md py-1 dark:text-white'>Full Stack Web3 Developer</h3>
            <p className='md:text-md text-sm py-3 leading-5 text-gray-600 dark:text-gray-300'> I’m looking to collaborate on startups which wanna change the life of our society with the help of web3 tech.</p>


            <div className='relative mt-10 w-40 h-40 lg:w-40 lg:h-40 mx-auto'>
              <Image className='rounded-full' src={devdel} />
            </div>

            <div className='text-xl flex justify-center gap-4 py-6 text-gray-700'>
              <a href='https://twitter.com/aelouragli' target='_blank'><AiFillTwitterCircle className='text-2xl cursor-pointer hover:text-teal-500 dark:text-white dark:hover:text-teal-300' /></a>
              <a href='https://github.com/devdelX' target='_blank'><AiFillGithub className='text-2xl cursor-pointer hover:text-teal-500 dark:text-white dark:hover:text-teal-300' /></a>
              <a href='https://linkedin.com/in/abdelprod/' target='_blank'><AiFillLinkedin className='text-2xl cursor-pointer hover:text-teal-500 dark:text-white dark:hover:text-teal-300' /></a>
            </div>


          </div>

          <ul className='flex justify-center dark:text-gray-200 gap-4 pt-4'>
                <li className='cursor-pointer hover:underline'><a href='https://abdelhadielouragli.medium.com/' target="_blank">Blog</a></li>
                <li className='cursor-pointer hover:underline'><a href='https://drive.google.com/file/d/1x1ZvFSkvvXo5rsv8DcYo4JtNiO4lh-GH/view' target="_blank">Resume</a></li>
                <li className='cursor-pointer hover:underline'><a href='mailto:abdelhadielouaraguli@gmail.com' target="_blank">Say Hey!</a></li>
              </ul>  
        </section>

      

      </main>
    </div>
  );
}
